name: clear logs
on:
  workflow_dispatch:
  schedule:
    # Every day at 1am
    - cron: "0 1 * * *"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: clear workflow runs logs
        uses: actions/github-script@v5
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
            });

            for (const run of runs.data.workflow_runs) {
                console.log(`Run id ${run.id} of '${run.name}' status '${run.status}'`)
                if (run.status === 'in_progress') {
                    continue;
                }

                await github.rest.actions.deleteWorkflowRunLogs({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    run_id: run.id,
                });

            }
