name: delete public logs

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: install npm dep
      run: npm i
    - name: run
      run: | 
        npm run start -- delete
      env:
        GITHUB_TOKEN: ${{ github.token }}
